name: lab13

services:

  nginx:
    image: nginx:1.26
    container_name: nginx

    ports:
      - "4001:80"

    volumes:
      - ./php:/var/www/html
      - ./nginx/nginx.config:/etc/nginx/conf.d/default.conf:ro

    depends_on:
      - php

    networks:
      - frontend
      - backend

  php:
    image: php:8.3-fpm
    container_name: php

    volumes:
      - ./php:/var/www/html

    expose:
      - "9000"

    networks:
      - backend

  mysql:
    image: mysql:8.4
    container_name: mysql

    environment:
      MYSQL_DATABASE: testdb
      MYSQL_USER: student

      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password

    secrets:
      - db_password
      - db_root_password

    volumes:
      - mysql_data:/var/lib/mysql

    expose:
      - "3306"

    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin:5.2.2
    container_name: phpmyadmin

    ports:
      - "6001:80"

    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306

    depends_on:
      - mysql

    networks:
      - frontend
      - backend

secrets:

  db_password:
    file: ./secrets/db_password.txt

  db_root_password:
    file: ./secrets/db_root_password.txt

volumes:

  mysql_data:

networks:

  frontend:
    driver: bridge

  backend:
    driver: bridge